name: Tag

on:
  push:
    tags:
      # Tags are in semantic versioning format.
      - 'v*.*.*'

permissions:
  id-token: write
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        uses: ../../actions/create-release@main
        with:
          secrets: ${{ toJSON(secrets) }}
          vars: ${{ toJSON(vars) }}
